# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43be2ad4772cc91ed9c3f241c3b11ad52fbea33f63e424061f5d164cd93d7a3e5a8cd3fa46a2c6f0eac552c3e5a5c730ec17a38b5445bf02733ec79d9490ed46

test:
  secret_key_base: b99ac05ca0a0385e8c548e996ba3a06d02e0c9924828aedc0ba00f8715afdb5fcc3f2a139d98116fa5d420482cf9860e8a94e1ec01bcd44f762161901ee14b24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
